### ISSUE TITLE
Reopening of file results in duplicate sender inputs & outputs (dynamo 2.0)

### ISSUE THREAD

**Issue by BCoop94** [speckleworks/SpeckleDynamo#56]
Each time a dynamo 2.0 script is reopened any saved speckle sender component has all its inputs and outputs duplicated.

**Comment by teocomi** [comment]
Hey @BCoop94 this happened to me too once, but couldn't consistently replicate it... Will look into it but if you can tell us how to replicate it it would be very helpful!

**Comment by ksobon** [comment]
@teocomi its caused by the exact version of Newtonsoft.Json library that you are using. It has to be v. 8.0.3. Don't ask me why.

**Comment by teocomi** [comment]
@ksobon I doubt that's the reason since I'm not including Newtonsoft.Json in the built...

**Comment by mjkkirschner** [comment]
for some reason, lets assume we don't know it yet - the json constructor is not being called when the graph is opened - this is usually caused by json.net of a different version being loaded and runtime attributes evaluating to different types.

ie - [JsonConstuctor of 8.03] is not equal to [JsonConstructor of 10.x] for example

**Comment by mjkkirschner** [comment]
one approach to fixing this which I have not tried, could be to combine both constructors into one and do the right thing in either case... 

Also have the user check for addins which are loading a different version of json.net - in the end the attributes are still compared at runtime, I'm not sure how frody will help here.

**Comment by mjkkirschner** [comment]
I would be interested to know what other addins the user has installed, since I think this extension has been working fine for others.

**Comment by teocomi** [comment]
@ksobon yes it's referencing v11 but it's not included in the release, so should be using whatever Dynamo comes with. 
It's probably as mike says, where there's another plugin/package creating the problem, but until we can consistently replicate it we won't know...

**Comment by ksobon** [comment]
@teocomi I understand that you are not including it in the release, but that's not the issue here. As far as I understand the issue is that Newtonsoft.Json is a strong-named assembly. When you referenced that in your solution, it will look for that assembly at runtime, and it will look for the specific version that was referenced in your solution (that's what strong-naming is for). So the fact that you are not including it doesn't make a difference here because I think that even though Revit loads v.8.0.3 your solution is looking for v.11.0.1 and it can't find it. 

I think that's what's going on here. 

I think there are couple of things to consider here as potential solutions: 
- if you have to have a dependency on v11.0.1, then try adding Assembly Resolver ex. `AppDomain.CurrentDomain.AssemblyResolve` or edit the `App.config` to point at the specific version dll in your app's sub-folder. I think you will have to actually start including the file. 
- if you don't have to have a dependency on v11.0.1, then consider changing it to v.8.0.3 which is the version used by Revit and Dynamo out of the box. That has proved to work relatively well for me in the past. 

Cheers!

**Comment by BCoop94** [comment]
Hi @teocomi,

- I installed speckle v1.2.2 however in installed packages it is listed as v1.0.1 
-  Dynamo 2.0.2
- So far the issue has occurred all the time upon reopening a save file.
- I can not replicate the issue in Dynamo sandbox.

**Comment by teocomi** [comment]
Thanks @BCoop94 , since you cannot replicate the issue in Dynamo sandbox, it makes me think there's a compatibility problem with another plugin/package. 
Can you please send me a screenshot of your installed Dynamo packages (Packages > Manage Packages...)?
A screenshot of the installed Revit plugins would also be helpful if you can share it.

**Comment by BCoop94** [comment]
@teocomi, 

![image](https://user-images.githubusercontent.com/37893741/52375139-0d2bd600-2ab3-11e9-87c5-9df3e504d392.png)
![image](https://user-images.githubusercontent.com/37893741/52376825-377f9280-2ab7-11e9-803e-23240af15a8e.png)
![image](https://user-images.githubusercontent.com/37893741/52376858-4f571680-2ab7-11e9-9b82-0f4815ccbcbb.png)

**Comment by pereiraTTW** [comment]
Hi @teocomi,

I just installed Revit 2019 (19.0.0.405), Dynamo 2.0.2 and the latest Speckle, and I'm getting the same behaviour.

I create a new sender, plugged some random values, and saved the Dynamo file. 

![image](https://user-images.githubusercontent.com/35948812/52387615-1337ac00-2adf-11e9-99e8-539cd87271a9.png)

We deployed our own server, so I tried the same in the Speckle Hestia server and inputs and outputs are repeated.

**Comment by teocomi** [comment]
Hi both @pereiraTTW @BCoop94 I still cannot replicate the bug, my guess is that it's a Revit plugin causing the problem.

Could you please either:
- temporarily disable all your revit plugins and try again
- send me a copy of your revit plugins and I'll try myself (if you can share them)

The Revit plugins are generally stored in a few locations:

\%appdata%\Autodesk\Revit\Addins\
C:\ProgramData\Autodesk\Revit\Addins\
C:\ProgramData\Autodesk\ApplicationPlugins\
C:\Program Files\Autodesk\Revit 20XX\AddIns\

To disable the plugins, just move them to another folder. To send them to me you can zip them and share them on Slack.

Thanks for your collaboration!

**Comment by mjkkirschner** [comment]
Also please post any green notifications in dynamos menu bar referring to Json

**Comment by alvpickmans** [comment]
just chiming in, I could replicate the same issue on Revit 2019.2, no extra add-in apart from anything that comes with Revit.
![image](https://user-images.githubusercontent.com/12413808/52472874-5734ba80-2b8c-11e9-96a9-ce97d05f6fe1.png)

I encounter the same problem in another package (https://forum.dynamobim.com/t/jsondata-package/19026/25), and solved it by downgrading Json.Net to 9.0.1.

**Comment by teocomi** [comment]
Okay so I could finally replicate the bug. Weirdly enough I had to *remove* some of my Revit plugins to do so... :/
I'll downgrade for now and publish an update while we check if there's a better solution...

@ksobon thanks for the heads up!
@mjkkirschner if I changed the logic of my constructors to handle this scenario, do you see any other possible conflict happening?

**Comment by pereiraTTW** [comment]
@teocomi, thanks for that. Please, keep us posted.

**Comment by teocomi** [comment]
@pereiraTTW this should work: https://github.com/speckleworks/SpeckleInstaller/releases/tag/v1.2.7
